import category_theory.action
       group_theory.semidirect_product
       free

open category_theory is_free_group semidirect_product

universe u
instance action_category_is_free_groupoid {G A : Type u} [group G] [mul_action G A] [is_free_group G] :
  is_free_groupoid (action_category G A) :=
let ac := (action_category.obj_equiv G A).symm in
let gens := λ x y, { a : gp_gens G // (gp_emb a) • ac x = ac y } in
let emb := λ x y (e : gens x y), (show x ⟶ y, from ⟨gp_emb e.val, e.property⟩) in
{ gpd_gens := gens,
  gpd_emb := emb,
  gpd_lift := begin
    introsI X _ f,
    set Y := (A → X) ⋊[my_mul_aut G A X] G,
    set f' : gp_gens G → Y := λ e, ⟨λ b,
      @f ⟨(), _⟩ ⟨(), b⟩ ⟨e, smul_inv_smul _ _⟩, gp_emb e⟩,
    rcases gp_lift f' with ⟨p, hp, up⟩,
    have sane : ∀ g : G, (p g).right = g,
    { set p' := right_hom.comp p,
      apply is_free_group_ext p',
      intro e, change (p _).right = _, rw ←hp },
    let F : action_category G A ⥤ single_obj X,
    { refine {
        obj := λ _, (),
        map := λ a b q, (p q.val).left (ac b),
        map_id' := _, map_comp' := _ },
      { intro a, change (p 1).left _ = 1,
        rw p.map_one, refl },
      { intros a b c f g,
        change (p (_ * _)).left _ = _ * _, rw p.map_mul, 
        change _ * _ = _ * _, congr,
        change (p f.val).left _ = _, congr,
        rw [inv_smul_eq_iff, sane],
        exact g.property.symm } },
    refine ⟨F, _, _⟩,
    { intros a b e,
      change f e = (p _).left _,
      rw ←hp,
      change f _ = f _,
      rcases a with ⟨⟨⟩, a⟩,
      rcases b with ⟨⟨⟩, b⟩,
      rcases e with ⟨e, h⟩,
      rw ←eq_inv_smul_iff at h,
      cases h, refl },
    { intros F' hF',
      have F'_congr : ∀ (a b c d : action_category G A) (f g : G)
        (h1 : (f • a.snd : A) = b.snd) (h2 : (g • c.snd : A) = d.snd),
          a = c → b = d → f = g → (F'.map ⟨f, h1⟩ : X) = (F'.map ⟨g, h2⟩ : X),
      { rintros _ _ _ _ _ _ _ _ ⟨⟩ ⟨⟩ ⟨⟩, refl },
      have ssmul : ∀ (g : G) (b : A), (g • (ac.symm $ g⁻¹ • b).snd : A) = (ac.symm b).snd,
      { apply smul_inv_smul },
      set p' : G →* Y := { 
        to_fun := λ g, ⟨λ b, F'.map ⟨g, ssmul g b⟩, g⟩,
        map_one' := begin
          congr, funext, change F'.map _ = 1,
          have : (1 : X) = F'.map (𝟙 (ac.symm b)),
          { rw F'.map_id, refl },
          rw this, apply F'_congr,
          { simp only [one_inv, one_smul] },
          all_goals { refl },
        end,
        map_mul' := begin
          intros g h, congr, funext,
          have : F'.map ⟨_, ssmul (g * h) b⟩ ==
            F'.map ⟨h, ssmul h (g⁻¹ • b)⟩ ≫ F'.map ⟨g, ssmul g b⟩,
          { apply heq_of_eq,
            rw ←F'.map_comp,
            apply F'_congr,
            { rw [mul_inv_rev, mul_smul] },
            all_goals { refl } },
          rw heq_iff_eq at this,
          exact this
        end },
      have : p' = p,
      { apply up,
        intro e,
        apply semidirect_product.ext,
        { funext, apply hF' },
        { refl } },
      apply functor.hext,
      { intro, apply unit.ext },
      rintros ⟨⟨⟩, a : A⟩ ⟨⟨⟩, b : A⟩ ⟨g, h : g • a = b⟩,
      change _ == (p _).left _,
      rw ←this,
      change F'.map _ == F'.map _,
      apply heq_of_eq,
      apply F'_congr,
      { congr, 
        rw eq_inv_smul_iff,
        exact h },
      all_goals { refl } }
  end,
  ind := begin
    intros,
    let Q : G → Prop := λ g, ∀ (x y : action_category G A) (z : x ⟶ y),
        g = subtype.val z → P z,
    have claim : ∀ g, Q g,
    { apply is_free_group_induction Q,
      { rintros e x y ⟨_, h⟩ ⟨⟩,
        change P (emb x y ⟨e, h⟩),
        apply base },
      { rintros ⟨⟨⟩, x: A⟩ ⟨⟨⟩, y⟩ ⟨_, h⟩ ⟨⟩,
        have : x = y,
        { change (1 : G) • x = y at h, simpa using h },
        cases this,
        apply id },
      { rintros g h gq hq x y ⟨_, prop⟩ ⟨⟩,
        let gh : x ⟶ y := ⟨g * h, prop⟩,
        change P gh,
        let mi : action_category G A := ac.symm (h • x.snd),
        let hh : x ⟶ mi := ⟨h, rfl⟩,
        let gg : mi ⟶ y := ⟨g, _⟩,
        have : gh = (hh ≫ gg),
        { ext, refl },
        rw this,
        apply comp,
        { apply hq, refl },
        { apply gq, refl },
        change _ • _ • _ = _,
        rw smul_smul,
        exact prop, },
      { rintros g gq x y ⟨_, prop⟩ ⟨⟩,
        let ii : y ⟶ x := ⟨g, _⟩,
        swap,
        { change _ • _ = _, symmetry, rw ←inv_smul_eq_iff, assumption },
        change P (inv ii),
        apply comp_1,
        apply gq,
        refl } },
    apply claim f.val, refl
  end }
